def dicionario
  {
    'AGUA RASA' => 'ÁGUA RASA',
    'GRAJAU' => 'GRAJAÚ',
    'CAPAO REDONDO' => 'CAPÃO REDONDO',
    'VILA JACUI'=>'VILA JACUÍ',
    'VILA CURUCA' => 'VILA CURUÇÁ',
    'VILA SONIA' => 'VILA SÔNIA',
    'SAO MIGUEL' => 'SÃO MIGUEL',
    'SAO MATEUS' => 'SÃO MATEUS',
    'JOSE BONIFACIO' => 'JOSÉ BONIFÁCIO',
    'SAO DOMINGOS' => 'SÃO DOMINGOS',
    'SAO LUCAS' => 'SÃO LUCAS',
    'CANGAIBA' => 'CANGAÍBA',
    'CIDADE LIDER' => 'CIDADE LÍDER',
    'CARRAO' => 'CARRÃO',
    'TREMEMBE' =>'TREMEMBÉ',
    'JACANA' => 'JAÇANÃ',
    'TATUAPE' => 'TATUAPÉ',
    'BELEM' => 'BELÉM',
    'JARDIM ANGELA' => 'JARDIM ÂNGELA',
    'JARDIM SAO LUIS' => 'JARDIM SÃO LUÍS',
    'BRAS' => 'BRÁS',
    'BRASILANDIA' => 'BRASILÂNDIA',
    'SANTA CECILIA' => 'SANTA CECÍLIA',
    'CONSOLACAO' => 'CONSOLAÇÃO',
    'SACOMA' => 'SACOMÃ',
    'SAO RAFAEL' => 'SÃO RAFAEL',
    'SE' => 'SÉ',
    'REPUBLICA' => 'REPÚBLICA',
    'BUTANTA' => 'BUTANTÃ',
    'JAGUARE' => 'JAGUARÉ',
    'JARAGUA' => 'JARAGUÁ',
    'SAUDE' => 'SAÚDE',
    'FREGUESIA DO O' => 'FREGUESIA DO Ó',
    'LIMAO' => 'LIMÃO'
  }
end

def butanta

  return ["ALTO DE PINHEIROS / SETOR 01",
  "ALTO DE PINHEIROS / SETOR 02",
  "ALTO DE PINHEIROS / SETOR 03",
  "ALTO DE PINHEIROS / SETOR 04",
  "BUTANTA / SETOR 01",
  "BUTANTA / SETOR 02",
  "BUTANTA / SETOR 03",
  "BUTANTA / SETOR 04",
  "ITAIM BIBI / SETOR 01",
  "ITAIM BIBI / SETOR 02",
  "ITAIM BIBI / SETOR 03",
  "ITAIM BIBI / SETOR 04",
  "JARDIM PAULISTA / SETOR 01",
  "JARDIM PAULISTA / SETOR 02",
  "JARDIM PAULISTA / SETOR 03",
  "MORUMBI / SETOR 01",
  "MORUMBI / SETOR 02",
  "MORUMBI / SETOR 03",
  "MORUMBI / SETOR 04",
  "PINHEIROS / SETOR 01",
  "PINHEIROS / SETOR 02",
  "PINHEIROS / SETOR 03",
  "PINHEIROS / SETOR 04",
  "RAPOSO TAVARES / SETOR 01",
  "RAPOSO TAVARES / SETOR 02",
  "RAPOSO TAVARES / SETOR 03",
  "RAPOSO TAVARES / SETOR 04",
  "RAPOSO TAVARES / SETOR 05",
  "RAPOSO TAVARES / SETOR 06",
  "RIO PEQUENO / SETOR 01",
  "RIO PEQUENO / SETOR 02",
  "RIO PEQUENO / SETOR 03",
  "RIO PEQUENO / SETOR 04",
  "RIO PEQUENO / SETOR 05",
  "VILA SONIA / SETOR 01",
  "VILA SONIA / SETOR 02",
  "VILA SONIA / SETOR 03",
  "VILA SONIA / SETOR 04"]
end

def campo_limpo
  return ["CAMPO LIMPO / SETOR 01",
    "CAMPO LIMPO / SETOR 02",
    "CAMPO LIMPO / SETOR 03",
    "CAMPO LIMPO / SETOR 04",
    "CAMPO LIMPO / SETOR 05",
    "CAMPO LIMPO / SETOR 06",
    "CAPAO REDONDO / SETOR 01",
    "CAPAO REDONDO / SETOR 02",
    "CAPAO REDONDO / SETOR 03",
    "CAPAO REDONDO / SETOR 04",
    "CAPAO REDONDO / SETOR 05",
    "CAPAO REDONDO / SETOR 06",
    "CAPAO REDONDO / SETOR 07",
    "CAPAO REDONDO / SETOR 08",
    "JARDIM ANGELA / SETOR 01",
    "JARDIM ANGELA / SETOR 02",
    "JARDIM ANGELA / SETOR 03",
    "JARDIM ANGELA / SETOR 04",
    "JARDIM ANGELA / SETOR 05",
    "JARDIM ANGELA / SETOR 06",
    "JARDIM ANGELA / SETOR 07",
    "JARDIM ANGELA / SETOR 08",
    "JARDIM ANGELA / SETOR 09",
    "JARDIM SAO LUIS / SETOR 01",
    "JARDIM SAO LUIS / SETOR 02",
    "JARDIM SAO LUIS / SETOR 03",
    "JARDIM SAO LUIS / SETOR 04",
    "JARDIM SAO LUIS / SETOR 05",
    "VILA ANDRADE / SETOR 01",
    "VILA ANDRADE / SETOR 02"]
  end

  def capela_do_socorro
    return ["CIDADE DUTRA / SETOR 01",
      "CIDADE DUTRA / SETOR 02",
      "CIDADE DUTRA / SETOR 03",
      "CIDADE DUTRA / SETOR 04",
      "CIDADE DUTRA / SETOR 05",
      "CIDADE DUTRA / SETOR 06",
      "CIDADE DUTRA / SETOR 07",
      "CIDADE DUTRA / SETOR 08",
      "CIDADE DUTRA / SETOR 09",
      "CIDADE DUTRA / SETOR 10",
      "GRAJAU / SETOR 01",
      "GRAJAU / SETOR 02",
      "GRAJAU / SETOR 03",
      "GRAJAU / SETOR 04",
      "GRAJAU / SETOR 05",
      "GRAJAU / SETOR 06",
      "GRAJAU / SETOR 07",
      "GRAJAU / SETOR 08",
      "GRAJAU / SETOR 09",
      "GRAJAU / SETOR 10",
      "GRAJAU / SETOR 11",
      "GRAJAU / SETOR 12",
      "GRAJAU / SETOR 13",
      "GRAJAU / SETOR 14",
      "GRAJAU / SETOR 15",
      "GRAJAU / SETOR 16",
      "GRAJAU / SETOR 17",
      "GRAJAU / SETOR 18",
      "MARSILAC / SETOR 01",
      "MARSILAC / SETOR 02",
      "PARELHEIROS / SETOR 01",
      "PARELHEIROS / SETOR 02",
      "PARELHEIROS / SETOR 03",
      "PARELHEIROS / SETOR 04",
      "PARELHEIROS / SETOR 05",
      "PARELHEIROS / SETOR 06",
      "PARELHEIROS / SETOR 07",
      "PARELHEIROS / SETOR 08",
      "PARELHEIROS / SETOR 09",
      "PARELHEIROS / SETOR 10",
      "PARELHEIROS / SETOR 11",
      "PARELHEIROS / SETOR 12",
      "PARELHEIROS / SETOR 13",
      "SOCORRO / SETOR 01",
      "SOCORRO / SETOR 02",
      "SOCORRO / SETOR 03",
      "SOCORRO / SETOR 04"]
    end
    def freguesia_brasilandia
      return ["BRASILANDIA / SETOR 01",
        "BRASILANDIA / SETOR 02",
        "BRASILANDIA / SETOR 03",
        "BRASILANDIA / SETOR 04",
        "BRASILANDIA / SETOR 05",
        "BRASILANDIA / SETOR 06",
        "BRASILANDIA / SETOR 07",
        "BRASILANDIA / SETOR 08",
        "BRASILANDIA / SETOR 09",
        "CACHOEIRINHA / SETOR 01",
        "CACHOEIRINHA / SETOR 02",
        "CACHOEIRINHA / SETOR 03",
        "CACHOEIRINHA / SETOR 04",
        "CACHOEIRINHA / SETOR 05",
        "CACHOEIRINHA / SETOR 06",
        "CASA VERDE / SETOR 01",
        "CASA VERDE / SETOR 02",
        "CASA VERDE / SETOR 03",
        "CASA VERDE / SETOR 04",
        "CASA VERDE / SETOR 05",
        "FREGUESIA DO O / SETOR 01",
        "FREGUESIA DO O / SETOR 02",
        "FREGUESIA DO O / SETOR 03",
        "FREGUESIA DO O / SETOR 04",
        "FREGUESIA DO O / SETOR 05",
        "FREGUESIA DO O / SETOR 06",
        "FREGUESIA DO O / SETOR 07",
        "FREGUESIA DO O / SETOR 08",
        "FREGUESIA DO O / SETOR 09",
        "FREGUESIA DO O / SETOR 10",
        "LIMAO / SETOR 01",
        "LIMAO / SETOR 04",
        "LIMAO / SETOR 03",
        "LIMAO / SETOR 04"]
      end
      def guaianases
        return ["CIDADE TIRADENTES / SETOR 01",
          "CIDADE TIRADENTES / SETOR 02",
          "CIDADE TIRADENTES / SETOR 03",
          "CIDADE TIRADENTES / SETOR 04",
          "CIDADE TIRADENTES / SETOR 05",
          "CIDADE TIRADENTES / SETOR 06",
          "CIDADE TIRADENTES / SETOR 07",
          "CIDADE TIRADENTES / SETOR 08",
          "GUAIANASES / SETOR 01",
          "GUAIANASES / SETOR 02",
          "GUAIANASES / SETOR 03",
          "GUAIANASES / SETOR 04",
          "LAJEADO / SETOR 01",
          "LAJEADO / SETOR 02",
          "LAJEADO / SETOR 03",
          "LAJEADO / SETOR 04",
          "LAJEADO / SETOR 05",
          "LAJEADO / SETOR 06",
          "LAJEADO / SETOR 07",
          "LAJEADO / SETOR 08"]
        end
        def ipiranga
          return ["BELA VISTA / SETOR 01",
            "BOM RETIRO / SETOR 01",
            "CAMBUCI / SETOR 01",
            "CAMBUCI / SETOR 02",
            "CONSOLACAO / SETOR 01",
            "CURSINO / SETOR 01",
            "CURSINO / SETOR 02",
            "CURSINO / SETOR 03",
            "CURSINO / SETOR 04",
            "IPIRANGA / SETOR 01",
            "IPIRANGA / SETOR 02",
            "IPIRANGA / SETOR 03",
            "IPIRANGA / SETOR 04",
            "IPIRANGA / SETOR 05",
            "LIBERDADE / SETOR 01",
            "MOEMA / SETOR 01",
            "MOEMA / SETOR 02",
            "REPUBLICA / SETOR 01",
            "SACOMA / SETOR 01",
            "SACOMA / SETOR 02",
            "SACOMA / SETOR 03",
            "SANTA CECILIA / SETOR 01",
            "SANTA CECILIA / SETOR 02",
            "SAO LUCAS / SETOR 01",
            "SAO LUCAS / SETOR 02",
            "SAO LUCAS / SETOR 03",
            "SAUDE / SETOR 01",
            "SAUDE / SETOR 02",
            "SAUDE / SETOR 03",
            "SE / SETOR 01",
            "VILA MARIANA / SETOR 01",
            "VILA MARIANA / SETOR 02",
            "VILA MARIANA / SETOR 03",
            "VILA MARIANA / SETOR 04",
            "VILA PRUDENTE / SETOR 01",
            "VILA PRUDENTE / SETOR 02"]
          end
          def itaquera
            return ["ARICANDUVA / SETOR 01",
              "ARICANDUVA / SETOR 02",
              "ARICANDUVA / SETOR 03",
              "ARICANDUVA / SETOR 04",
              "CARRAO / SETOR 01",
              "CARRAO / SETOR 02",
              "CARRAO / SETOR 03",
              "CIDADE LIDER / SETOR 01",
              "CIDADE LIDER / SETOR 02",
              "CIDADE LIDER / SETOR 03",
              "CIDADE LIDER / SETOR 04",
              "CIDADE LIDER / SETOR 05",
              "CIDADE LIDER / SETOR 06",
              "ITAQUERA / SETOR 01",
              "ITAQUERA / SETOR 02",
              "ITAQUERA / SETOR 03",
              "ITAQUERA / SETOR 04",
              "ITAQUERA / SETOR 05",
              "ITAQUERA / SETOR 06",
              "ITAQUERA / SETOR 07",
              "JOSE BONIFACIO / SETOR 01",
              "JOSE BONIFACIO / SETOR 02",
              "JOSE BONIFACIO / SETOR 03",
              "JOSE BONIFACIO / SETOR 04",
              "JOSE BONIFACIO / SETOR 05",
              "JOSE BONIFACIO / SETOR 06",
              "PARQUE DO CARMO / SETOR 01",
              "PARQUE DO CARMO / SETOR 02",
              "PARQUE DO CARMO / SETOR 03",
              "PARQUE DO CARMO / SETOR 04",
              "PARQUE DO CARMO / SETOR 05",
              "VILA FORMOSA / SETOR 01",
              "VILA FORMOSA / SETOR 02",
              "VILA FORMOSA / SETOR 03",
              "VILA FORMOSA / SETOR 04",
              "VILA FORMOSA / SETOR 05"]
            end
            def jacana_tremembe
              return ["JACANA / SETOR 01",
                "JACANA / SETOR 02",
                "JACANA / SETOR 03",
                "JACANA / SETOR 04",
                "JACANA / SETOR 05",
                "MANDAQUI / SETOR 01",
                "MANDAQUI / SETOR 02",
                "MANDAQUI / SETOR 03",
                "MANDAQUI / SETOR 04",
                "MANDAQUI / SETOR 05",
                "SANTANA / SETOR 01",
                "SANTANA / SETOR 02",
                "SANTANA / SETOR 03",
                "SANTANA / SETOR 04",
                "SANTANA / SETOR 05",
                "SANTANA / SETOR 06",
                "SANTANA / SETOR 07",
                "TREMEMBE / SETOR 01",
                "TREMEMBE / SETOR 02",
                "TREMEMBE / SETOR 03",
                "TREMEMBE / SETOR 04",
                "TREMEMBE / SETOR 05",
                "TREMEMBE / SETOR 06",
                "TREMEMBE / SETOR 07",
                "TUCURUVI / SETOR 01",
                "TUCURUVI / SETOR 02",
                "TUCURUVI / SETOR 03",
                "TUCURUVI / SETOR 04",
                "TUCURUVI / SETOR 05",
                "VILA GUILHERME / SETOR 01",
                "VILA GUILHERME / SETOR 02",
                "VILA GUILHERME / SETOR 03",
                "VILA MARIA / SETOR 01",
                "VILA MARIA / SETOR 02",
                "VILA MARIA / SETOR 03",
                "VILA MARIA / SETOR 04",
                "VILA MARIA / SETOR 05",
                "VILA MARIA / SETOR 06",
                "VILA MEDEIROS / SETOR 01",
                "VILA MEDEIROS / SETOR 02",
                "VILA MEDEIROS / SETOR 03",
                "VILA MEDEIROS / SETOR 04",
                "VILA MEDEIROS / SETOR 05"]
              end
              def penha
                return ["AGUA RASA / SETOR 01",
                  "AGUA RASA / SETOR 02",
                  "AGUA RASA / SETOR 03",
                  "ARTUR ALVIM / SETOR 01",
                  "ARTUR ALVIM / SETOR 02",
                  "ARTUR ALVIM / SETOR 03",
                  "ARTUR ALVIM / SETOR 04",
                  "ARTUR ALVIM / SETOR 05",
                  "BELEM / SETOR 01",
                  "BELEM / SETOR 02",
                  "BELEM / SETOR 03",
                  "BRAS / SETOR 01",
                  "BRAS / SETOR 02",
                  "BRAS / SETOR 03",
                  "BRAS / SETOR 04",
                  "BRAS / SETOR 05",
                  "CANGAIBA / SETOR 01",
                  "CANGAIBA / SETOR 02",
                  "CANGAIBA / SETOR 03",
                  "CANGAIBA / SETOR 04",
                  "CANGAIBA / SETOR 05",
                  "ERMELINO MATARAZZO / SETOR 01",
                  "ERMELINO MATARAZZO / SETOR 02",
                  "ERMELINO MATARAZZO / SETOR 03",
                  "ERMELINO MATARAZZO / SETOR 04",
                  "MOOCA / SETOR 01",
                  "MOOCA / SETOR 02",
                  "MOOCA / SETOR 03",
                  "PARI / SETOR 01",
                  "PENHA / SETOR 01",
                  "PENHA / SETOR 02",
                  "PENHA / SETOR 03",
                  "PONTE RASA / SETOR 01",
                  "PONTE RASA / SETOR 02",
                  "PONTE RASA / SETOR 03",
                  "PONTE RASA / SETOR 04",
                  "TATUAPE / SETOR 01",
                  "TATUAPE / SETOR 02",
                  "VILA MATILDE / SETOR 01",
                  "VILA MATILDE / SETOR 02",
                  "VILA MATILDE / SETOR 03",
                  "VILA MATILDE / SETOR 04",
                  "VILA MATILDE / SETOR 05"]
                end
                def pirituba
                  return ["ANHANGUERA / SETOR 01",
                    "ANHANGUERA / SETOR 02",
                    "ANHANGUERA / SETOR 03",
                    "ANHANGUERA / SETOR 04",
                    "ANHANGUERA / SETOR 05",
                    "ANHANGUERA / SETOR 06",
                    "ANHANGUERA / SETOR 07",
                    "ANHANGUERA / SETOR 08",
                    "BARRA FUNDA / SETOR 01",
                    "BRASILANDIA / SETOR 01",
                    "BRASILANDIA / SETOR 02",
                    "BRASILANDIA / SETOR 03",
                    "BRASILANDIA / SETOR 04",
                    "BRASILANDIA / SETOR 05",
                    "BRASILANDIA / SETOR 06",
                    "BRASILANDIA / SETOR 07",
                    "BRASILANDIA / SETOR 08",
                    "BRASILANDIA / SETOR 09",
                    "JAGUARA / SETOR 01",
                    "JAGUARE / SETOR 01",
                    "JAGUARE / SETOR 02",
                    "JARAGUA / SETOR 01",
                    "JARAGUA / SETOR 02",
                    "JARAGUA / SETOR 03",
                    "JARAGUA / SETOR 04",
                    "JARAGUA / SETOR 05",
                    "JARAGUA / SETOR 06",
                    "JARAGUA / SETOR 07",
                    "JARAGUA / SETOR 08",
                    "JARAGUA / SETOR 09",
                    "LAPA / SETOR 01",
                    "LAPA / SETOR 02",
                    "LAPA / SETOR 03",
                    "PERDIZES / SETOR 01",
                    "PERDIZES / SETOR 02",
                    "PERUS / SETOR 01",
                    "PERUS / SETOR 02",
                    "PERUS / SETOR 03",
                    "PIRITUBA / SETOR 01",
                    "PIRITUBA / SETOR 02",
                    "PIRITUBA / SETOR 03",
                    "PIRITUBA / SETOR 04",
                    "PIRITUBA / SETOR 05",
                    "PIRITUBA / SETOR 06",
                    "SAO DOMINGOS / SETOR 01",
                    "SAO DOMINGOS / SETOR 02",
                    "SAO DOMINGOS / SETOR 03",
                    "SAO DOMINGOS / SETOR 04",
                    "VILA LEOPOLDINA / SETOR 01",
                    "VILA LEOPOLDINA / SETOR 02"]
                  end
                  def santo_amaro
                    return ["CAMPO BELO / SETOR 01",
                      "CAMPO BELO / SETOR 02",
                      "CAMPO GRANDE / SETOR 01",
                      "CAMPO GRANDE / SETOR 02",
                      "CAMPO GRANDE / SETOR 03",
                      "CAMPO GRANDE / SETOR 04",
                      "CAMPO GRANDE / SETOR 05",
                      "CIDADE ADEMAR / SETOR 01",
                      "CIDADE ADEMAR / SETOR 02",
                      "CIDADE ADEMAR / SETOR 03",
                      "CIDADE ADEMAR / SETOR 04",
                      "CIDADE ADEMAR / SETOR 05",
                      "CIDADE ADEMAR / SETOR 06",
                      "JABAQUARA / SETOR 01",
                      "JABAQUARA / SETOR 02",
                      "JABAQUARA / SETOR 03",
                      "JABAQUARA / SETOR 04",
                      "JABAQUARA / SETOR 05",
                      "JABAQUARA / SETOR 06",
                      "PEDREIRA / SETOR 01",
                      "PEDREIRA / SETOR 02",
                      "PEDREIRA / SETOR 03",
                      "PEDREIRA / SETOR 04",
                      "PEDREIRA / SETOR 05",
                      "SANTO AMARO / SETOR 01",
                      "SANTO AMARO / SETOR 02",
                      "SANTO AMARO / SETOR 03",
                      "SANTO AMARO / SETOR 04"]
                    end
                    def sao_mateus
                      return ["IGUATEMI / SETOR 01",
                        "IGUATEMI / SETOR 02",
                        "IGUATEMI / SETOR 03",
                        "IGUATEMI / SETOR 04",
                        "IGUATEMI / SETOR 05",
                        "IGUATEMI / SETOR 06",
                        "IGUATEMI / SETOR 07",
                        "IGUATEMI / SETOR 08",
                        "SAO MATEUS / SETOR 01",
                        "SAO MATEUS / SETOR 02",
                        "SAO MATEUS / SETOR 03",
                        "SAO MATEUS / SETOR 04",
                        "SAO MATEUS / SETOR 05",
                        "SAO MATEUS / SETOR 06",
                        "SAO MATEUS / SETOR 07",
                        "SAO MATEUS / SETOR 08",
                        "SAO MATEUS / SETOR 09",
                        "SAO RAFAEL / SETOR 01",
                        "SAO RAFAEL / SETOR 02",
                        "SAO RAFAEL / SETOR 03",
                        "SAO RAFAEL / SETOR 04",
                        "SAO RAFAEL / SETOR 05",
                        "SAO RAFAEL / SETOR 06",
                        "SAO RAFAEL / SETOR 07",
                        "SAO RAFAEL / SETOR 08",
                        "SAPOPEMBA / SETOR 01",
                        "SAPOPEMBA / SETOR 02",
                        "SAPOPEMBA / SETOR 03",
                        "SAPOPEMBA / SETOR 04",
                        "SAPOPEMBA / SETOR 05",
                        "SAPOPEMBA / SETOR 06",
                        "SAPOPEMBA / SETOR 07",
                        "SAPOPEMBA / SETOR 08",
                        "SAPOPEMBA / SETOR 09",
                        "SAPOPEMBA / SETOR 10"]
                      end
                      def sao_miguel
                        return ["ITAIM PAULISTA / SETOR 01",
                          "ITAIM PAULISTA / SETOR 02",
                          "ITAIM PAULISTA / SETOR 03",
                          "ITAIM PAULISTA / SETOR 04",
                          "ITAIM PAULISTA / SETOR 05",
                          "ITAIM PAULISTA / SETOR 06",
                          "ITAIM PAULISTA / SETOR 07",
                          "ITAIM PAULISTA / SETOR 08",
                          "ITAIM PAULISTA / SETOR 09",
                          "ITAIM PAULISTA / SETOR 10",
                          "JARDIM HELENA / SETOR 01",
                          "JARDIM HELENA / SETOR 02",
                          "JARDIM HELENA / SETOR 03",
                          "JARDIM HELENA / SETOR 04",
                          "JARDIM HELENA / SETOR 05",
                          "JARDIM HELENA / SETOR 06",
                          "LAJEADO / SETOR 01",
                          "LAJEADO / SETOR 02",
                          "LAJEADO / SETOR 03",
                          "LAJEADO / SETOR 04",
                          "LAJEADO / SETOR 05",
                          "LAJEADO / SETOR 06",
                          "LAJEADO / SETOR 07",
                          "LAJEADO / SETOR 08",
                          "SAO MIGUEL / SETOR 01",
                          "SAO MIGUEL / SETOR 02",
                          "SAO MIGUEL / SETOR 03",
                          "SAO MIGUEL / SETOR 04",
                          "SAO MIGUEL / SETOR 05",
                          "SAO MIGUEL / SETOR 06",
                          "SAO MIGUEL / SETOR 07",
                          "SAO MIGUEL / SETOR 08",
                          "VILA CURUCA / SETOR 01",
                          "VILA CURUCA / SETOR 02",
                          "VILA CURUCA / SETOR 03",
                          "VILA CURUCA / SETOR 04",
                          "VILA CURUCA / SETOR 05",
                          "VILA CURUCA / SETOR 06",
                          "VILA CURUCA / SETOR 07",
                          "VILA CURUCA / SETOR 08",
                          "VILA CURUCA / SETOR 09",
                          "VILA CURUCA / SETOR 10",
                          "VILA CURUCA / SETOR 11",
                          "VILA JACUI / SETOR 01",
                          "VILA JACUI / SETOR 02",
                          "VILA JACUI / SETOR 03",
                          "VILA JACUI / SETOR 04",
                          "VILA JACUI / SETOR 05",
                          "VILA JACUI / SETOR 06",
                          "VILA JACUI / SETOR 07",
                          "VILA MARIA / SETOR 01",
                          "VILA MARIA / SETOR 02",
                          "VILA MARIA / SETOR 03",
                          "VILA MARIA / SETOR 04",
                          "VILA MARIA / SETOR 05",
                          "VILA MARIA / SETOR 06"]
                        end
                        def setores(dre)
                          return butanta if dre == 1
                          return campo_limpo if dre == 2
                          return capela_do_socorro if dre == 3
                          return freguesia_brasilandia if dre == 4
                          return guaianases if dre == 5
                          return ipiranga if dre == 6
                          return itaquera if dre == 7
                          return jacana_tremembe if dre == 8
                          return penha if dre == 9
                          return pirituba if dre == 10
                          return santo_amaro if dre == 11
                          return sao_mateus if dre == 12
                          return sao_miguel if dre == 13
                        end
